apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  completions: 10
  parallelism: 3
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: tools-container
          image: amsy810/tools:v2.0
          command: ["sleep"]
          args: ["60"]
      restartPolicy: Never
